[ids]
*

[main]

kpdot = layer(ichingbottomlayer)

[ichingbottomlayer]

kp0 = overload(bottomtrigram0, macro(C-S-u 2 6 3 0 enter))
kp1 = overload(bottomtrigram1, macro(C-S-u 2 6 3 4 enter))
kp2 = overload(bottomtrigram2, macro(C-S-u 2 6 3 2 enter))
kp3 = overload(bottomtrigram3, macro(C-S-u 2 6 3 6 enter))
kp4 = overload(bottomtrigram4, macro(C-S-u 2 6 3 1 enter))
kp5 = overload(bottomtrigram5, macro(C-S-u 2 6 3 5 enter))
kp6 = overload(bottomtrigram6, macro(C-S-u 2 6 3 3 enter))
kp7 = overload(bottomtrigram7, macro(C-S-u 2 6 3 7 enter))

# base trigram ☰
[bottomtrigram0]
0 = macro(C-S-u 4 d c 0 enter)
1 = macro(C-S-u 4 d c 8 enter)
2 = macro(C-S-u 4 d c d enter)
3 = macro(C-S-u 4 d d 9 enter)
4 = macro(C-S-u 4 d e a enter)
5 = macro(C-S-u 4 d c 4 enter)
6 = macro(C-S-u 4 d e 1 enter)
7 = macro(C-S-u 4 d c a enter)

# base trigram ☴
[bottomtrigram1]
0 = macro(C-S-u 4 d e b enter)
1 = macro(C-S-u 4 d f 8 enter)
2 = macro(C-S-u 4 d f 1 enter)
3 = macro(C-S-u 4 d d 1 enter)
4 = macro(C-S-u 4 d d b enter)
5 = macro(C-S-u 4 d e f enter)
6 = macro(C-S-u 4 d d f enter)
7 = macro(C-S-u 4 d e d enter)

# base trigram ☲
[bottomtrigram2]
0 = macro(C-S-u 4 d c c enter)
1 = macro(C-S-u 4 d e 4 enter)
2 = macro(C-S-u 4 d d d enter)
3 = macro(C-S-u 4 d d 5 enter)
4 = macro(C-S-u 4 d f 0 enter)
5 = macro(C-S-u 4 d f e enter)
6 = macro(C-S-u 4 d f 6 enter)
7 = macro(C-S-u 4 d e 3 enter)

# base trigram ☶
[bottomtrigram3]
0 = macro(C-S-u 4 d e 0 enter)
1 = macro(C-S-u 4 d f 4 enter)
2 = macro(C-S-u 4 d f 7 enter)
3 = macro(C-S-u 4 d f 3 enter)
4 = macro(C-S-u 4 d d e enter)
5 = macro(C-S-u 4 d e 6 enter)
6 = macro(C-S-u 4 d f d enter)
7 = macro(C-S-u 4 d c e enter)

# base trigram ☱
[bottomtrigram4]
0 = macro(C-S-u 4 d c 9 enter)
1 = macro(C-S-u 4 d f c enter)
2 = macro(C-S-u 4 d e 5 enter)
3 = macro(C-S-u 4 d e 8 enter)
4 = macro(C-S-u 4 d f 9 enter)
5 = macro(C-S-u 4 d f b enter)
6 = macro(C-S-u 4 d f 5 enter)
7 = macro(C-S-u 4 d d 2 enter)

# base trigram ☵
[bottomtrigram5]
0 = macro(C-S-u 4 d c 5 enter)
1 = macro(C-S-u 4 d f a enter)
2 = macro(C-S-u 4 d f f enter)
3 = macro(C-S-u 4 d c 3 enter)
4 = macro(C-S-u 4 d e e enter)
5 = macro(C-S-u 4 d d c enter)
6 = macro(C-S-u 4 d e 7 enter)
7 = macro(C-S-u 4 d c 6 enter)

# base trigram ☳
[bottomtrigram6]
0 = macro(C-S-u 4 d d 8 enter)
1 = macro(C-S-u 4 d e 9 enter)
2 = macro(C-S-u 4 d d 4 enter)
3 = macro(C-S-u 4 d d a enter)
4 = macro(C-S-u 4 d d 0 enter)
5 = macro(C-S-u 4 d c 2 enter)
6 = macro(C-S-u 4 d f 2 enter)
7 = macro(C-S-u 4 d d 7 enter)

# base trigram ☷
[bottomtrigram7]
0 = macro(C-S-u 4 d c b enter)
1 = macro(C-S-u 4 d d 3 enter)
2 = macro(C-S-u 4 d e 2 enter)
3 = macro(C-S-u 4 d d 6 enter)
4 = macro(C-S-u 4 d e c enter)
5 = macro(C-S-u 4 d c 7 enter)
6 = macro(C-S-u 4 d c f enter)
7 = macro(C-S-u 4 d c 1 enter)
